version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"  # ADICIONADO: Para redirecionamento
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -k https://localhost:443 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file: .env
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm7.3 && curl -f http://localhost:9000/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress

networks:
  inception:
    driver: bridge